name: Vulnerability report
description: Create a vulnerability report to ensure security
title: Vulnerability report
labels: [security]
assignees: []

body:
  - type: textarea
    id: describe-vulnerability
    attributes:
      label: Describe the vulnerability
      description: A clear and concise description of what the vulnerability is.
    validations:
      required: true

  - type: textarea
    id: vulnerable-code
    attributes:
      label: Vulnerable Code
      description: Paste the vulnerable code snippet here.
      placeholder: |
        ```code
        rem Your vulnerable code here
        ```
    validations:
      required: true

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: Explain how you think this could be fixed. If you have specific code for the fix, submit a pull request.
      placeholder: Describe your proposed fix or workaround.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Relevant logs, references, or steps to reproduce (if needed).