name: Release

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install zip tar wget -y

      - name: Get short commit hash
        id: get_commit
        run: echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Create stable release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          name: stable-${{ env.COMMIT_HASH }}
          tag_name: stable-${{ env.COMMIT_HASH }}
          body: |
            Automated stable release for commit `${{ env.COMMIT_HASH }}`
          files: |
            src/compiler.bat
            test/test.bat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}